version: '3.8'

services:
  ws4sqlite:
    image: germanorizzo/ws4sqlite:latest
    container_name: ws4sqlite
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ALLOWED_ORIGIN="*"
    volumes:
      - /mnt/DockerHome/myDir:/data
      - ./production.db:/production.db
      - ./production.yaml:/production.yaml
    command: --db /production.db --bind-host studybuddydb.camerondugan.com
